var path = require('path');
var fs = require('fs');
var marked = require('marked');
var yaml = require('js-yaml');

var version = require('../package.json').version;


/**
 * Constructor accepts a document (as a string) and a path from which to
 * include external dependencies (stylesheets, scripts, etc)
 *
 * @param {string} file The input document's path
 * @param {Object} options settings object
 *     listed in the cleaver document
 * @param {any} log Logger.
 * @constructor
 */
function rvl(file, opts, log) {
  let filePath = file.toString();
  let options = opts || {};
  log.debug(filePath)

  let contents = fs.readFileSync(filePath, 'utf8');
  log.debug(contents)

  let slides = contents.split("\n---\n");
  log.debug(slides)
  let docOpts = {}
  if (slides[0].startsWith("---")) {
    docOpts = yaml.safeLoad(slides.shift().slice(3)) || {}
  }
  slides = slides.map(function (txt) {
    return marked(txt)
  })
  log.debug(slides)
  log.debug(docOpts)


  let document = genDoc(slides, docOpts)
  log.debug(document)
  fs.writeFileSync(options.out, document)
}

function genDoc(slides, opts) {
  let rvlv = opts.revealVersion || "3.8.0";
  let slidesHTML = "<section>"+ slides.join("</section><section>") + "</section>"
  return `
<!DOCTYPE html>
<html lang="${ opts.lang || "en" }">
<head><meta charset="UTF-8">
<title>${ opts.title || "RevealJS Slideshow generated by rvl-cli" }</title>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/reveal.js/${ rvlv }/css/reveal.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0/css/theme/black.min.css'>
</head>
<body translate="no">

<div class="reveal">
<div class="slides">
${
  slidesHTML
}
</div>
</div>
<script src='https://cdnjs.cloudflare.com/ajax/libs/reveal.js/${ rvlv }/js/reveal.min.js'></script>
<script id="rendered-js">
      Reveal.initialize({
  controls: true,
  progress: true,
  history: true,
  center: true,
  dependencies: [
    {
      src:
        "https://joelellis.github.io/RevealJS-notes/notes.js",
      async: true
    },
    {
      src:
        "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0/plugin/highlight/highlight.min.js",
      async: true
    }
  ]
});
    </script>
</body>
</html>
`
}


module.exports = rvl;